language: ruby
cache: bundler
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
notifications:
  email:
   - dcleal@redhat.com
   - raphael.pinson@camptocamp.com
env:
  # Most tests with oldest supported ruby-augeas
  - PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0
  - PUPPET=3.0.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0
  - PUPPET=3.2.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0
  - PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0
  # Test the latest ruby-augeas (~>)
  - PUPPET=3.2.0 RUBY_AUGEAS=0.5
  - PUPPET=3.4 RUBY_AUGEAS=0.5
  # Test other versions of Augeas
  - PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=0.10.0
  - PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=0.10.0
  - PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.0.0
  - PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.0.0
  - PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0
  - PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0
  - PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.2.0
  - PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.2.0
  # Issue #83: test old Augeas with new lenses
  - PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.0.0 LENSES=HEAD
  - PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0 LENSES=HEAD
  - PUPPET=3.4 RUBY_AUGEAS=0.5 AUGEAS=1.0.0 LENSES=HEAD
  - PUPPET=3.4 RUBY_AUGEAS=0.5 AUGEAS=1.1.0 LENSES=HEAD
matrix:
  fast_finish: true
  exclude:
    # No support for Ruby 2.0 before Puppet 3.2.0 and ruby-augeas 0.5
    - rvm: 2.0.0
      env: PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0
    - rvm: 2.0.0
      env: PUPPET=3.0.0 RUBY_AUGEAS=0.3.0
    - rvm: 2.0.0
      env: PUPPET=3.2.0 RUBY_AUGEAS=0.3.0
    - rvm: 2.0.0
      env: PUPPET=3.4 RUBY_AUGEAS=0.3.0
    - rvm: 2.0.0
      env: PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=0.10.0
    - rvm: 2.0.0
      env: PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=0.10.0
    - rvm: 2.0.0
      env: PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.0.0
    - rvm: 2.0.0
      env: PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.0.0
    - rvm: 2.0.0
      env: PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0
    - rvm: 2.0.0
      env: PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0
    - rvm: 2.0.0
      env: PUPPET=2.7.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.2.0
    - rvm: 2.0.0
      env: PUPPET=3.0.0 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0
    - rvm: 2.0.0
      env: PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.2.0
    - rvm: 2.0.0
      env: PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.0.0 LENSES=HEAD
    - rvm: 2.0.0
      env: PUPPET=3.4 RUBY_AUGEAS=0.3.0 AUGEAS=1.1.0 LENSES=HEAD
install:
  - "travis_retry ./.travis.sh"
script:
  - AUGEAS_LENS_LIB=augeas/lenses bundle exec rake
